execute pathogen#infect()
syntax enable
filetype plugin indent on

let mapleader = ","

colorscheme wal

set rtp+=~/.fzf

set number

set autoindent smartindent      " turn on auto/smart indenting
set smarttab                    " make <tab> and <backspace> smarter
set tabstop=8                   " tabstops of 8
set shiftwidth=8                " indents of 8
set backspace=eol,start,indent  " allow backspacing over indent, eol, & start
set undolevels=1000             " number of forgivable mistakes
set updatecount=100             " write swap file to disk every 100 chars
set complete=.,w,b,u,U,t,i,d    " do lots of scanning on tab completion
set viminfo=%100,'100,/100,h,\"500,:100,n~/.vim/viminfo
set directory=~/.vim/swap

set undodir=~/.vim/undo
set undofile

set diffopt=filler,iwhite       " ignore all whitespace and sync

set mouse=a
set showcmd
set number relativenumber
set colorcolumn=80
set ruler
set noerrorbells
set ls=2
set wildmenu
set hidden

set ignorecase
set smartcase
set hlsearch
set incsearch
set showmatch

set diffopt=filler,iwhite       " ignore all white space and sync


" restore cursor position
autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" delete all trailing whitespaces on save
autocmd BufWritePre * %s/\s\+$//e

autocmd FileType c nnoremap <Leader>i ggdG:r ~/.vim/file_templates/cf_template.c<cr>ggdd5Ga
autocmd FileType cpp nnoremap <Leader>i ggdG:r ~/.vim/file_templates/cf_template.cpp<cr>ggdd10Ga

autocmd FileType c nnoremap <Leader>c :!gcc -Og -g -Wall -Wextra "%" -lm && ./a.out<cr>
autocmd FileType cpp nnoremap <Leader>c :!g++ -Og -g -Wall -Wextra "%" -lm && ./a.out<cr>
autocmd FileType c,cpp nnoremap <Leader>r :!./a.out<cr>

autocmd FileType html setlocal shiftwidth=2 tabstop=2 expandtab
autocmd FileType javascript setlocal shiftwidth=2 tabstop=2 expandtab
autocmd FileType typescript setlocal shiftwidth=2 tabstop=2 expandtab
autocmd FileType haskell setlocal shiftwidth=4 tabstop=4 expandtab

nnoremap <Leader>m :make<cr>
map <Leader>n :cn<cr>
map <Leader>p :cp<cr>

nnoremap <silent> <cr> :noh<cr><cr>

" toggle paste mode
nnoremap <F2> :set paste! nopaste?<cr>

inoremap <Nul> <C-n>

nnoremap <C-f> :FZF<cr>

map <C-p> :bp<cr>
map <C-n> :bn<cr>

