#!/bin/sh

while read file
do
        case "$1" in
        "C-c")
                xclip -selection clipboard -t image/png "$file" ;;
        "C-w")
		wal -l -i "$file" ;;
        "C-e")
		wal -i "$file" ;;
	"C-d")
		mv "$file" /tmp ;;
        esac
done

